#!/bin/bash

if [[ -f "/usr/share/oh-my-zsh/oh-my-zsh.sh" ]]; then
    sudo sed -i "s/\${ZDOTDIR:-\$HOME}/\${ZDOTDIR:-\$HOME\/.config\/zsh}/" /usr/share/oh-my-zsh/oh-my-zsh.sh
    tput setaf 3
    echo 'ZDOTDIR : path changed'
    tput sgr0
fi

